version: "3.3"
services:
  apps:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "9000:9000"
    depends_on:
      - mongodb
    links:
      - mongodb
    working_dir: /apps
    command: ["pnpm", "dev"]

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: app
    restart: always
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
    driver: local
